### ISSUE TITLE
Adaptive Icons are broken

### ISSUE THREAD

**Issue by ashuramaruzxc** [IndusAryan/twitter-patches#13]
Here's currently how it is:
<details><summary>Image.png</summary>
<img src="https://github.com/IndusAryan/twitter-patches/assets/72100551/52ca3f32-118c-46ee-ac7e-e6d10241db2a" alt="Screenshot_52ca3f32-118c-46ee-ac7e-e6d10241db2a.png">
</details>
Expected behavior: Working Adaptive Icon

**Comment by IndusAryan** [comment]
the patch is not broken , the adaptive one was never added, the monochrome icon will come tomorrow. i dont use the youtube revanced icon method instead i use long term maintainable drawable system and it gets hard to produce a perfect monochrome icon.
 plus the crimera parts cause crash and make app unusable, i have found it is NoClassDefFound error, and will try to solve it. until i have rolled back and made feb 15 patches as latest.
this repo is more focused on cosmetic changes fyi.

**Comment by IndusAryan** [comment]
@ashuramaruzxc the monochrome icon has been added as seen in readme image, it is present in all the 3 icon sets, and crash has been fixed, due to mod menu use crimera integrations, but i would suggest to use crimera patches to patch apk first and then patch it again with icons , material design and branding. (it takes 3 min extra fr)
